# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MaginstantApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MaginstantApp
  pod 'Firebase/Core'

  target 'MaginstantApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MaginstantAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
